# Generated by Django 3.2.8 on 2021-10-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
