# Generated by Django 3.2.8 on 2021-10-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211019_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='album_name',
            new_name='name',
        ),
    ]
