# Generated by Django 3.2.8 on 2021-10-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_album_name_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
