# Generated by Django 3.2.8 on 2021-10-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_track_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
