# Generated by Django 3.2.8 on 2021-11-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_feature',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
