# Generated by Django 3.2.8 on 2021-11-08 09:47

from django.db import migrations

def link_artists(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Artist = apps.get_model('products', 'Artist')
    for product in Product.objects.all():
        artist_name, created = Artist.objects.get_or_create(name=product.artist_name, defaults={'name': 'Default Name'})
        product.artist_link = artist_name
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211108_0938'),
    ]

    operations = [
        migrations.RunPython(link_artists),
    ]
