# Generated by Django 3.2.8 on 2021-11-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='artist_link',
            new_name='artist_name',
        ),
    ]
