# Generated by Django 3.2.8 on 2021-11-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_artist_link_product_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hifi_deal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
