# Generated by Django 3.2.8 on 2021-11-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_is_hifi_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='track_list',
        ),
    ]
