# Generated by Django 3.2.8 on 2021-11-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_track_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist_display_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
