# Generated by Django 3.2.8 on 2021-11-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_artist_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
